---
title: "Car accidents of all types between 1999 and 2007"
output:
  flexdashboard::flex_dashboard:
    navbar:
      - title: "title"
    orientation: columns
    vertical_layout: fill
    theme: lumen
---

```{r}
library(dplyr)
library(leaflet)
library(crosstalk)
library(here)
library(purrr)
library(crosstalk)

load(here::here("data/act_crashes_sa2.rda"))

sd <- SharedData$new(act_crashes_sa2)
```

Map {data-icon="fa-globe-asia"}
=====================================

Column {data-height=2}
-------------------------------------

### Filters

```{r}

filter_slider(
  id = "decile",
  column = "decile",
  label = "Filter areas based on decile rank",
  sharedData = sd,
  step = 1,
  round = TRUE,
  ticks = TRUE
)

filter_checkbox(
  id = 'bins',
  label = 'Filter areas based on top and/or bottom 10%',
  sharedData = sd,
  group = ~bins
)
```

```{r} 
bscols(
filter_select(
  id = "sa2_name16",
  label="Filter areas based on name",
  sharedData = sd,
  group = ~sa2_name16
)
)
```

### Datatable

```{r}

sd %>% DT::datatable(
  #filter = "top",
  extensions = c("Scroller", "Buttons"),
  rownames = TRUE,
  colnames = c('Statistical Area (SA2)' = 'sa2_name16',
               'Area km^2' = 'areasqkm16',
               'Accidents' = 'crashes',
               'Accidents/km^2' = 'crashes_sq_km',
               'Decile rankings' = 'decile'),
  style = "bootstrap",
  class = "compact",
  width = "100%",
  options = list(
    dom = "Blrtip",
    deferRender = TRUE,
    scrollY = 300,
    scroller = TRUE,
    columnDefs = list(
      list(targets = c(0,1,2,4,5,6,7,8,9,10,11,13,14,16,19), visible = FALSE)),
    buttons = list("csv", "excel"))
)


```

Column {data-width=600}
-------------------------------------

### Maps

```{r}

library(leafem)

sd %>% leaflet(
  options = leafletOptions(
    zoomControl = FALSE,
    attributionControl = FALSE
  )
) %>% 
  setView(
    lng = 149,
    lat = -35.46,
    zoom = 10
  ) %>% 
  addProviderTiles(providers$CartoDB.PositronNoLabels,
                   group = "Light",
                   options = tileOptions(
                     minZoom = 8, maxZoom = 11,
                     useCache = TRUE, crossOrigin = TRUE
                   )) %>% 
  addPolygons(
    stroke = TRUE,
    color = "black",
    dashArray = "1",
    opacity = 1,
    weight = 0.5, 
    smoothFactor = 0.2,
    fillColor = "transparent",
    fillOpacity = 0.7,
    label = ~sa2_name16,  # SLA name as a hover label
    highlight = highlightOptions(
      color = "#008B8B",
      dashArray = "3",
      opacity = 1,
      weight = 2,
      fillOpacity = 0.7,
      fillColor = "#008B8B",
      bringToFront = TRUE
    )
  ) %>% 
  addCircleMarkers(
    lng = ~cent_lng,
    lat = ~cent_lat,
    stroke = TRUE,
    weight = 0.5,
    #radius = 3.75,
    color = "transparent",
    fillColor = "transparent",
    label = purrr::map(glue::glue("<span style ='color:{act_crashes_sa2$color}'>{act_crashes_sa2$crashes_sq_km}<span>"), htmltools::HTML),
    #label = ~round(crashes_sq_km, 2),
    labelOptions = labelOptions(
      noHide = TRUE,
      direction = "center",
      textOnly = TRUE,
      style = list(
        "font-family" = "Arial",
        "font-weight" = "bolder",
        "font-size" = "10px"
      )
    )
  ) %>% addMouseCoordinates()
  
  
```

```{css}

.navbar-inverse {
  background-color: #008B8B;
  border-color: #008B8B;
}
.navbar-inverse .navbar-brand {
  color: black; # main title color (default)
}
.navbar-inverse .navbar-brand:hover,
.navbar-inverse .navbar-brand:focus {
  color: yellow;
  background-color: transparent;
}
.navbar-inverse .navbar-text {
  color: #777;
}
.navbar-inverse .navbar-nav > li > a {
  color: #777;
}
.navbar-inverse .navbar-nav > li > a:hover,
.navbar-inverse .navbar-nav > li > a:focus {
  color: #333;
  background-color: transparent;
}
.navbar-inverse .navbar-nav > .active > a,
.navbar-inverse .navbar-nav > .active > a:hover,
.navbar-inverse .navbar-nav > .active > a:focus {
  color: #555;
  background-color: #e7e7e7;
}
.navbar-inverse .navbar-nav > .disabled > a,
.navbar-inverse .navbar-nav > .disabled > a:hover,
.navbar-inverse .navbar-nav > .disabled > a:focus {
  color: #ccc;
  background-color: transparent;
}
.navbar-inverse .navbar-toggle {
  border-color: #ddd;
}
.navbar-inverse .navbar-toggle:hover,
.navbar-inverse .navbar-toggle:focus {
  background-color: #ddd;
}
.navbar-inverse .navbar-toggle .icon-bar {
  background-color: #888;
}
.navbar-inverse .navbar-collapse,
.navbar-inverse .navbar-form {
  border-color: #e7e7e7;
}
.navbar-inverse .navbar-nav > .open > a,
.navbar-inverse .navbar-nav > .open > a:hover,
.navbar-inverse .navbar-nav > .open > a:focus {
  color: #555;
  background-color: #e7e7e7;
}
@media (max-width: 767px) {
  .navbar-inverse .navbar-nav .open .dropdown-menu > li > a {
    color: #777;
  }
  .navbar-inverse .navbar-nav .open .dropdown-menu > li > a:hover,
  .navbar-inverse .navbar-nav .open .dropdown-menu > li > a:focus {
    color: #333;
    background-color: transparent;
  }
  .navbar-inverse .navbar-nav .open .dropdown-menu > .active > a,
  .navbar-inverse .navbar-nav .open .dropdown-menu > .active > a:hover,
  .navbar-inverse .navbar-nav .open .dropdown-menu > .active > a:focus {
    color: #555;
    background-color: #e7e7e7;
  }
  .navbar-inverse .navbar-nav .open .dropdown-menu > .disabled > a,
  .navbar-inverse .navbar-nav .open .dropdown-menu > .disabled > a:hover,
  .navbar-inverse .navbar-nav .open .dropdown-menu > .disabled > a:focus {
    color: #ccc;
    background-color: transparent;
  }
}
.navbar-inverse .navbar-link {
  color: #777;
}
.navbar-inverse .navbar-link:hover {
  color: #333;
}
.navbar-inverse .btn-link {
  color: #777;
}
.navbar-inverse .btn-link:hover,
.navbar-inverse .btn-link:focus {
  color: #333;
}
.navbar-inverse .btn-link[disabled]:hover,
fieldset[disabled] .navbar-inverse .btn-link:hover,
.navbar-inverse .btn-link[disabled]:focus,
fieldset[disabled] .navbar-inverse .btn-link:focus {
  color: #ccc;
}



body {
  padding-top: 60px;
  background: rgba(0,0,0,0.015);
}

.section.sidebar {
  top: 51px;

  /* background-color: #f5f5f5; */
  background-color: #f8f8f8;
}

.value-box {
  color: inherit;
}

.bg-primary {
  background-color: rgba(51, 122, 183, 0.4);
}

.nav-tabs-custom > .nav-tabs > li.active {
  border-top-color: rgba(51, 122, 183, 0.4);
}
```





